# Generated by Django 4.0.6 on 2022-08-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentMethod',
            new_name='paymentmethod',
        ),
    ]
