# Generated by Django 4.0.6 on 2022-08-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_paymentmethod_order_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postalCode',
            new_name='postalcode',
        ),
    ]
